var cadastroEmpresas =
    [{

        "id": 1,
        "CompanyName": "Loja01",
        "Location": "Contagem",
        "idade": 25,
        "vaga_data": "Desenvolvedor Java",
        "Descricao": "Necessario forte exepriencia na linguagem java, necessidade de atuacao em warroom",
        "topics": ["DSA self paced course",
            "Machine learning",
            "Web development",]

    },
    {

        "id": 2,
        "CompanyName": "Loja02",
        "Location": "Contagem",
        "idade": 25,
        "vaga_data": "Desenvolvedor Java",
        "Descricao": "Necessario forte exepriencia na linguagem java, necessidade de atuacao em warroom",
        "topics": ["DSA self paced course",
            "Machine learning",
            "Web development",]
    },

    {
        "id": 3,
        "CompanyName": "Loja03",
        "Location": "Belo Horizonte",
        "idade": 25,
        "vaga_data": "Desenvolvedor Java",
        "Descricao": "Necessario forte exepriencia na linguagem py, necessidade de atuacao em warroom",
        "topics": ["DSA self paced course",
            "Machine learning",
            "Web development",]
    },

    {
        "id": 4,
        "CompanyName": "Loja04",
        "Location": "Belo Horizonte",
        "idade": 25,
        "vaga_data": "Desenvolvedor Java",
        "Descricao": "Necessario forte exepriencia na linguagem java, necessidade de atuacao em warroom",
        "topics": ["DSA self paced course",
            "Machine learning",
            "Web development",]

    },


    {
        "id": 5,
        "CompanyName": "Loja05",
        "Location": "Betim",
        "idade": 23,
        "vaga_data": "Desenvolvedor Python",
        "Descricao": "Necessario forte exepriencia na linguagem python, necessidade de atuacao em warroom",
        "topics": ["DSA self paced course",
            "Machine learning",
            "Web development",]



    },


    {
        "id": 6,
        "CompanyName": "Loja06",
        "Location": "Betim",
        "idade": 23,
        "vaga_data": "Desenvolvedor Java",
        "Descricao": "Necessario forte exepriencia na linguagem java, necessidade de atuacao em warroom",
        "topics": ["DSA self paced course",
            "Machine learning",
            "Web development",]

    },


    {


        "id": 7,
        "CompanyName": "Loja07",
        "Location": "Betim",
        "idade": 23,
        "vaga_data": "Desenvolvedor Python",
        "Descricao": "Necessario forte exepriencia na linguagem python, necessidade de atuacao em warroom",
        "topics": ["DSA self paced course",
            "Machine learning",
            "Web development",]
    },
    {

    "id": 8,
        "CompanyName": "Loja08",
        "Location": "Betim",
        "idade": 23,
        "vaga_data": "Desenvolvedor Python",
        "Descricao": "Necessario forte exepriencia na linguagem python, necessidade de atuacao em warroom",
        "topics": ["DSA self paced course",
            "Machine learning",
            "Web development",]

    }

    ];


    // CADASTROS DOS USUARIOS E SUAS FUNÇÕES

    let = cadastroUsuarios [

        {  
            "id": 1,
        "CompanyName": "Christiano barbosa",
        "Location": "Betim",
        "idade": 61,
        "vaga_data": "Desenvolvedor Python",
        "Descricao": "Necessario forte exepriencia na linguagem python, necessidade de atuacao em warroom",
        "topics": ["DSA self paced course",
            "Machine learning",
            "Web development",]


        },
        
        {  
            "id": 2,
        "CompanyName": "Thiago Marques",
        "Location": "Betim",
        "idade": 23,
        "vaga_data": "Desenvolvedor Python",
        "Descricao": "Necessario forte exepriencia na linguagem python, necessidade de atuacao em warroom",
        "topics": ["DSA self paced course",
            "Machine learning",
            "Web development",]


        },
      
        {  
            "id": 3,
        "CompanyName": "Diego geraldo",
        "Location": "Betim",
        "idade": 23,
        "vaga_data": "Desenvolvedor Python",
        "Descricao": "Necessario forte exepriencia na linguagem python, necessidade de atuacao em warroom",
        "topics": ["DSA self paced course",
            "Machine learning",
            "Web development",]


        },

        {  
            "id": 4,
        "CompanyName": "viviane Maques",
        "Location": "Betim",
        "idade": 23,
        "vaga_data": "Desenvolvedor Python",
        "Descricao": "Necessario forte exepriencia na linguagem python, necessidade de atuacao em warroom",
        "topics": ["DSA self paced course",
            "Machine learning",
            "Web development",]


        },



        {  
            "id": 5,
        "CompanyName": "Clara Eckel",
        "Location": "Betim",
        "idade": 23,
        "vaga_data": "Desenvolvedor Python",
        "Descricao": "Necessario forte exepriencia na linguagem python, necessidade de atuacao em warroom",
        "topics": ["DSA self paced course",
            "Machine learning",
            "Web development",]


        },



        {  
            "id": 6,
        "CompanyName": "Kethlen lorrayne",
        "Location": "Betim",
        "idade": 23,
        "vaga_data": "Desenvolvedor Python",
        "Descricao": "Necessario forte exepriencia na linguagem python, necessidade de atuacao em warroom",
        "topics": ["DSA self paced course",
            "Machine learning",
            "Web development",]


        },



        {  
            "id": 7,
        "CompanyName": "joão Pedro",
        "Location": "Betim",
        "idade": 23,
        "vaga_data": "Desenvolvedor Python",
        "Descricao": "Necessario forte exepriencia na linguagem python, necessidade de atuacao em warroom",
        "topics": ["DSA self paced course",
            "Machine learning",
            "Web development",]


        },



        {  
            "id": 8,
        "CompanyName": "Neto Oliveira",
        "Location": "Betim",
        "idade": 23,
        "vaga_data": "Desenvolvedor Python",
        "Descricao": "Necessario forte exepriencia na linguagem python, necessidade de atuacao em warroom",
        "topics": ["DSA self paced course",
            "Machine learning",
            "Web development",]


        },

        {  
            "id": 9,
        "CompanyName": "cleber batista",
        "Location": "Betim",
        "idade": 23,
        "vaga_data": "Desenvolvedor Python",
        "Descricao": "Necessario forte exepriencia na linguagem python, necessidade de atuacao em warroom",
        "topics": ["DSA self paced course",
            "Machine learning",
            "Web development",]


        },

        {  
            "id": 10,
        "CompanyName": "gustavo silva",
        "Location": "Betim",
        "idade": 23,
        "vaga_data": "Desenvolvedor Python",
        "Descricao": "Necessario forte exepriencia na linguagem python, necessidade de atuacao em warroom",
        "topics": ["DSA self paced course",
            "Machine learning",
            "Web development",]


        },


        {  
            "id": 11,
        "CompanyName": "pablo marques",
        "Location": "Betim",
        "idade": 23,
        "vaga_data": "Desenvolvedor Python",
        "Descricao": "Tenho forte exepriencia na linguagem python, atuo em warroom",
        "topics": ["DSA self paced course",
            "Machine learning",
            "Web development",]


        },


        {  
            "id": 12,
        "CompanyName": "Pedro augusto",
        "Location": "Betim",
        "idade": 23,
        "vaga_data": "Desenvolvedor Python",
        "Descricao": "Tenho forte exepriencia na linguagem python, atuo em warroom",
        "topics": ["DSA self paced course",
            "Machine learning",
            "Web development",]


        },


        {  
            "id": 13,
        "CompanyName": "maicon oliveira",
        "Location": "Betim",
        "idade": 23,
        "vaga_data": "Desenvolvedor Python",
        "Descricao": "Tenho forte exepriencia na linguagem python, atuo em warroom",
        "topics": ["DSA self paced course",
            "Machine learning",
            "Web development",]


        },

        {  
            "id": 14,
        "CompanyName": "monique alienz",
        "Location": "Betim",
        "idade": 23,
        "vaga_data": "Desenvolvedor Python",
        "Descricao": "Tenho forte exepriencia na linguagem python, atuo em warroom",
        "topics": ["DSA self paced course",
            "Machine learning",
            "Web development",]


        },

        {  
            "id": 15,
        "CompanyName": "alianz parque",
        "Location": "Betim",
        "idade": 23,
        "vaga_data": "Desenvolvedor Python",
        "Descricao": "Tenho forte exepriencia na linguagem python, atuo em warroom",
        "topics": ["DSA self paced course",
            "Machine learning",
            "Web development",]


        },

        {  
            "id": 16,
        "CompanyName": "higor gomes",
        "Location": "Betim",
        "idade": 23,
        "vaga_data": "Desenvolvedor Python",
        "Descricao": "Necessario forte exepriencia na linguagem python, necessidade de atuacao em warroom",
        "topics": ["DSA self paced course",
            "Machine learning",
            "Web development",]


        },

        {  
            "id": 17,
        "CompanyName": "joaquim Oliveira",
        "Location": "Betim",
        "idade": 23,
        "vaga_data": "Desenvolvedor Python",
        "Descricao": "Tenho forte exepriencia na linguagem python, atuo em warroom",
        "topics": ["DSA self paced course",
            "Machine learning",
            "Web development",]


        },


        {  
            "id": 18,
        "CompanyName": "carol  Oliveira",
        "Location": "Betim",
        "idade": 23,
        "vaga_data": "Desenvolvedor Python",
        "Descricao": "tenho forte exepriencia na linguagem python,  atuo em warroom",
        "topics": ["DSA self paced course",
            "Machine learning",
            "Web development",]


        },


        {  
            "id": 19,
        "CompanyName": "barcelos vasconcelos",
        "Location": "Betim",
        "idade": 23,
        "vaga_data": "Desenvolvedor Python",
        "Descricao": "Tenho forte exepriencia na linguagem python, necessidade de atuacao em warroom",
        "topics": ["DSA self paced course",
            "Machine learning",
            "Web development",]


        },



        {  
            "id": 20,
        "CompanyName": "leo pereira",
        "Location": "Betim",
        "idade": 23,
        "vaga_data": "Desenvolvedor Python",
        "Descricao": "Tenho forte exepriencia na linguagem python, necessidade de atuacao em warroom",
        "topics": ["DSA self paced course",
            "Machine learning",
            "Web development",]


        }

    ];










